-- ========================================================================
-- GLOBAL SOLUTION 2025 - O FUTURO DO TRABALHO
-- Plataforma de Upskilling/Reskilling
-- Script compatível com H2 e Oracle
-- ========================================================================

-- ========================================================================
-- 1. TABELA USUARIOS
-- Armazena os profissionais/alunos da plataforma
-- ========================================================================
CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    area_atuacao VARCHAR(100),
    nivel_carreira VARCHAR(50),
    data_cadastro DATE NOT NULL
);

-- ========================================================================
-- 2. TABELA TRILHAS
-- Armazena as trilhas de aprendizagem disponíveis
-- ========================================================================
CREATE TABLE trilhas (
    id_trilha BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    nivel VARCHAR(50) NOT NULL CHECK (nivel IN ('INICIANTE', 'INTERMEDIARIO', 'AVANCADO')),
    carga_horaria INT NOT NULL CHECK (carga_horaria > 0),
    foco_principal VARCHAR(100)
);

-- ========================================================================
-- 3. TABELA MATRICULAS
-- Relacionamento entre usuários e trilhas (inscrições)
-- ========================================================================
CREATE TABLE matriculas (
    id_matricula BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    trilha_id BIGINT NOT NULL,
    data_inscricao DATE NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT fk_matricula_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_matricula_trilha FOREIGN KEY (trilha_id) REFERENCES trilhas(id_trilha) ON DELETE CASCADE
);

-- ========================================================================
-- ÍNDICES PARA PERFORMANCE
-- ========================================================================
CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_area ON usuarios(area_atuacao);
CREATE INDEX idx_trilhas_nivel ON trilhas(nivel);
CREATE INDEX idx_trilhas_foco ON trilhas(foco_principal);
CREATE INDEX idx_matriculas_usuario ON matriculas(usuario_id);
CREATE INDEX idx_matriculas_trilha ON matriculas(trilha_id);
CREATE INDEX idx_matriculas_status ON matriculas(status);

-- ========================================================================
-- SEEDS - DADOS INICIAIS
-- ========================================================================

-- ========================================================================
-- USUARIOS (5 exemplos)
-- ========================================================================
INSERT INTO usuarios (nome, email, area_atuacao, nivel_carreira, data_cadastro) VALUES
('Ana Silva', 'ana.silva@email.com', 'Desenvolvimento de Software', 'PLENO', TO_DATE('2024-01-15', 'YYYY-MM-DD'));

INSERT INTO usuarios (nome, email, area_atuacao, nivel_carreira, data_cadastro) VALUES
('Carlos Mendes', 'carlos.mendes@email.com', 'Análise de Dados', 'JUNIOR', TO_DATE('2024-02-20', 'YYYY-MM-DD'));

INSERT INTO usuarios (nome, email, area_atuacao, nivel_carreira, data_cadastro) VALUES
('Beatriz Santos', 'beatriz.santos@email.com', 'Marketing Digital', 'SENIOR', TO_DATE('2024-03-10', 'YYYY-MM-DD'));

INSERT INTO usuarios (nome, email, area_atuacao, nivel_carreira, data_cadastro) VALUES
('Diego Oliveira', 'diego.oliveira@email.com', 'Recursos Humanos', 'PLENO', TO_DATE('2024-04-05', 'YYYY-MM-DD'));

INSERT INTO usuarios (nome, email, area_atuacao, nivel_carreira, data_cadastro) VALUES
('Fernanda Costa', 'fernanda.costa@email.com', 'Gestão de Projetos', 'SENIOR', TO_DATE('2024-05-12', 'YYYY-MM-DD'));

-- ========================================================================
-- TRILHAS (10 exemplos - IA, Dados, Soft Skills, etc)
-- ========================================================================

-- Trilhas de IA
INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Fundamentos de Inteligência Artificial', 'Introdução aos conceitos básicos de IA, Machine Learning e suas aplicações no mercado de trabalho.', 'INICIANTE', 40, 'Inteligência Artificial');

INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Machine Learning Avançado', 'Técnicas avançadas de ML, Deep Learning e Neural Networks para projetos complexos.', 'AVANCADO', 80, 'Inteligência Artificial');

-- Trilhas de Dados
INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Análise de Dados com Python', 'Aprenda a analisar e visualizar dados usando Python, Pandas e Matplotlib.', 'INICIANTE', 50, 'Análise de Dados');

INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Big Data e Data Engineering', 'Trabalhe com grandes volumes de dados usando Spark, Hadoop e ferramentas de cloud.', 'INTERMEDIARIO', 70, 'Engenharia de Dados');

-- Trilhas de Desenvolvimento
INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Desenvolvimento Web Full Stack', 'Construa aplicações web completas usando React, Node.js e bancos de dados modernos.', 'INTERMEDIARIO', 100, 'Desenvolvimento Web');

INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('DevOps e Cloud Computing', 'Domine práticas DevOps, CI/CD, Docker, Kubernetes e cloud (AWS, Azure, GCP).', 'AVANCADO', 90, 'DevOps');

-- Trilhas de Soft Skills
INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Liderança e Gestão de Equipes', 'Desenvolva habilidades de liderança, comunicação e gestão de pessoas para o futuro do trabalho.', 'INTERMEDIARIO', 30, 'Soft Skills');

INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Agilidade e Metodologias Ágeis', 'Aprenda Scrum, Kanban e outras metodologias ágeis para ambientes de trabalho modernos.', 'INICIANTE', 25, 'Metodologias Ágeis');

-- Trilhas de Negócios
INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Product Management 2030', 'Gestão de produtos digitais com foco em IA, dados e experiência do usuário.', 'INTERMEDIARIO', 60, 'Gestão de Produtos');

INSERT INTO trilhas (nome, descricao, nivel, carga_horaria, foco_principal) VALUES
('Transformação Digital nas Empresas', 'Como liderar processos de transformação digital e inovação organizacional.', 'AVANCADO', 45, 'Transformação Digital');

-- ========================================================================
-- MATRICULAS (10 exemplos - variados)
-- ========================================================================

-- Ana Silva (Desenvolvedora) - 2 trilhas
INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(1, 1, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 'CONCLUIDA');      -- Fundamentos de IA (concluída)

INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(1, 5, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'EM_ANDAMENTO');   -- Desenvolvimento Web Full Stack (em andamento)


-- Carlos Mendes (Analista de Dados) - 2 trilhas
INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(2, 3, TO_DATE('2024-06-10', 'YYYY-MM-DD'), 'EM_ANDAMENTO');   -- Análise de Dados com Python (em andamento)

INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(2, 8, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 'EM_ANDAMENTO');   -- Agilidade e Metodologias Ágeis (em andamento)


-- Beatriz Santos (Marketing) - 2 trilhas
INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(3, 7, TO_DATE('2024-05-20', 'YYYY-MM-DD'), 'CONCLUIDA');      -- Liderança e Gestão de Equipes (concluída)

INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(3, 10, TO_DATE('2024-08-01', 'YYYY-MM-DD'), 'EM_ANDAMENTO');  -- Transformação Digital (em andamento)


-- Diego Oliveira (RH) - 2 trilhas
INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(4, 7, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 'EM_ANDAMENTO');   -- Liderança e Gestão de Equipes (em andamento)

INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(4, 8, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 'CONCLUIDA');      -- Agilidade e Metodologias Ágeis (concluída)

-- Fernanda Costa (Gestão de Projetos) - 2 trilhas
INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(5, 6, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 'CANCELADA');      -- DevOps e Cloud Computing (cancelada)

INSERT INTO matriculas (usuario_id, trilha_id, data_inscricao, status) VALUES
(5, 9, TO_DATE('2024-08-05', 'YYYY-MM-DD'), 'EM_ANDAMENTO');   -- Product Management 2030 (em andamento)