-- ============================================================================
-- Global Solution 2025 - O Futuro do Trabalho
-- Plataforma de Upskilling/Reskilling
-- ============================================================================
-- Migration V1: Criação das tabelas
-- ============================================================================

-- Tabela: USUARIOS
-- Armazena os profissionais/alunos cadastrados na plataforma
CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    area_atuacao VARCHAR(100),
    nivel_carreira VARCHAR(50),
    data_cadastro DATE NOT NULL
);

-- Tabela: TRILHAS
-- Armazena as trilhas de aprendizagem disponíveis
CREATE TABLE trilhas (
    id_trilha BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    nivel VARCHAR(50) NOT NULL CHECK (nivel IN ('INICIANTE', 'INTERMEDIARIO', 'AVANCADO')),
    carga_horaria INT NOT NULL CHECK (carga_horaria > 0),
    foco_principal VARCHAR(100)
);

-- Tabela: COMPETENCIAS
-- Armazena as competências do futuro (tecnológicas e humanas)
CREATE TABLE competencias (
    id_competencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    categoria VARCHAR(100),
    descricao TEXT
);

-- Tabela: TRILHA_COMPETENCIA (N:N)
-- Relacionamento entre trilhas e competências
CREATE TABLE trilha_competencia (
    trilha_id BIGINT NOT NULL,
    competencia_id BIGINT NOT NULL,
    PRIMARY KEY (trilha_id, competencia_id),
    CONSTRAINT fk_trilha FOREIGN KEY (trilha_id) REFERENCES trilhas(id_trilha) ON DELETE CASCADE,
    CONSTRAINT fk_competencia FOREIGN KEY (competencia_id) REFERENCES competencias(id_competencia) ON DELETE CASCADE
);

-- Tabela: MATRICULAS
-- Armazena as inscrições de usuários em trilhas
CREATE TABLE matriculas (
    id_matricula BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    trilha_id BIGINT NOT NULL,
    data_inscricao DATE NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (status IN ('EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT fk_matricula_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_matricula_trilha FOREIGN KEY (trilha_id) REFERENCES trilhas(id_trilha) ON DELETE CASCADE
);

-- ============================================================================
-- Índices para melhorar performance
-- ============================================================================

-- Índice para busca por email (usado frequentemente)
CREATE INDEX idx_usuarios_email ON usuarios(email);

-- Índice para busca por área de atuação
CREATE INDEX idx_usuarios_area ON usuarios(area_atuacao);

-- Índice para busca por nível de trilha
CREATE INDEX idx_trilhas_nivel ON trilhas(nivel);

-- Índice para busca por categoria de competência
CREATE INDEX idx_competencias_categoria ON competencias(categoria);

-- Índice para busca de matrículas por usuário
CREATE INDEX idx_matriculas_usuario ON matriculas(usuario_id);

-- Índice para busca de matrículas por trilha
CREATE INDEX idx_matriculas_trilha ON matriculas(trilha_id);

-- Índice para busca de matrículas por status
CREATE INDEX idx_matriculas_status ON matriculas(status);

-- ============================================================================
-- Comentários nas tabelas (documentação)
-- ============================================================================

COMMENT ON TABLE usuarios IS 'Profissionais/alunos cadastrados na plataforma de Upskilling/Reskilling';
COMMENT ON TABLE trilhas IS 'Trilhas de aprendizagem focadas nas competências do futuro';
COMMENT ON TABLE competencias IS 'Competências do futuro (IA, Dados, Soft Skills, etc)';
COMMENT ON TABLE trilha_competencia IS 'Relacionamento N:N entre trilhas e competências';
COMMENT ON TABLE matriculas IS 'Inscrições de usuários em trilhas de aprendizagem';